pipeline{
    agent null
    stages{
        stage('Test') {
            steps {
                build(job: 'test_vm2')
            }
        }
        stage('Pre-Prod') {
            steps {
                build(job: 'pre-prod_vm3')
            }
        }
    }
}